export const menuCrepes = [
  {
    id: 1,
    menuTitle: "Crepe nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 2,
    menuTitle: "Crepe nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 3,
    menuTitle: "Crepe nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 4,
    menuTitle: "Crepe nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 5,
    menuTitle: "Crepe nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 6,
    menuTitle: "Crepe nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 7,
    menuTitle: "Crepe nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 8,
    menuTitle: "Crepe nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 9,
    menuTitle: "Crepe nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 10,
    menuTitle: "Crepe nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
];

export const menuGauffres = [
  {
    id: 1,
    menuTitle: "Gauffre nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 2,
    menuTitle: "Gauffre nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 3,
    menuTitle: "Gauffre nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 4,
    menuTitle: "Gauffre nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 5,
    menuTitle: "Gauffre nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 6,
    menuTitle: "Gauffre nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 7,
    menuTitle: "Gauffre nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 8,
    menuTitle: "Gauffre nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 9,
    menuTitle: "Gauffre nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 10,
    menuTitle: "Gauffre nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
];

export const menuSnack = [
  {
    id: 1,
    menuTitle: "Snack nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 2,
    menuTitle: "Snack nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 3,
    menuTitle: "Snack nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 4,
    menuTitle: "Snack nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 5,
    menuTitle: "Snack nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 6,
    menuTitle: "Snack nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 7,
    menuTitle: "Snack nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 8,
    menuTitle: "Snack nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 9,
    menuTitle: "Snack nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 10,
    menuTitle: "Snack nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
];

export const boissons = [
  { title: "Coca", price: 2.5, imageUrl: "" },
  { title: "Orangina", price: 2.5, imageUrl: "" },
  { title: "Fanta", price: 2.5, imageUrl: "" },
  { title: "Sprite", price: 2.5, imageUrl: "" },
  { title: "Ice Tea", price: 2.5, imageUrl: "" },
  { title: "Schweppes", price: 2.5, imageUrl: "" },
  { title: "Nestea", price: 2.5, imageUrl: "" },
  { title: "Perrier", price: 2.5, imageUrl: "" },
  { title: "Eau plate", price: 2.5, imageUrl: "" },
  { title: "Eau gazeuse", price: 2.5, imageUrl: "" },
  { title: "Jus de fruit", price: 2.5, imageUrl: "" },
]