const menuCrepes = [
  {
    id: 1,
    menuTitle: "Crepe nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 2,
    menuTitle: "Crepe nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 3,
    menuTitle: "Crepe nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 4,
    menuTitle: "Crepe nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 5,
    menuTitle: "Crepe nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 6,
    menuTitle: "Crepe nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 7,
    menuTitle: "Crepe nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 8,
    menuTitle: "Crepe nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 9,
    menuTitle: "Crepe nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 10,
    menuTitle: "Crepe nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
];

const menuGauffres = [
  {
    id: 1,
    menuTitle: "Gauffre nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 2,
    menuTitle: "Gauffre nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 3,
    menuTitle: "Gauffre nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 4,
    menuTitle: "Gauffre nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 5,
    menuTitle: "Gauffre nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 6,
    menuTitle: "Gauffre nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 7,
    menuTitle: "Gauffre nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 8,
    menuTitle: "Gauffre nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 9,
    menuTitle: "Gauffre nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
  {
    id: 10,
    menuTitle: "Gauffre nature",
    price: 25,
    description: "« Des crêpes natures à garnir comme on veut, avec du salé ou du sucré au choix. »",
    imageUrl: "/plat.webp",
  },
];